server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: something
            client-secret: something
            scope:
              - email
              - profile

          facebook:
            client-id: something
            client-secret: something
            scope:
              - email
              - public_profile

          naver:
            client-id: something
            client-secret: something
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 로그인 창 주소
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 발급 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보 조회 uri
            user-name-attribute: response # 회원정보 json이 response: {} 형태로 되어 있음